# deleted from resources folder "template" and "static": dont need html
spring:
  datasource:
    username: root
    password: pwd1
    url: jdbc:mysql://localhost:3306/serverdb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #format all log
        format_sql: true
      show-sql: true